### ISSUE TITLE
Consider adding test?

### ISSUE THREAD

**Issue by R1j1t** [seedlit/dsm2dtm#1]
Hi @seedlit, 

I think if you will add tests to package, it will help in people understanding the use case easily. Also, it would help track the development of the package in the future. Here is a good line:
> ... other developers want to see tests in your software before they take it seriously is yet another reason for you to start writing tests.
-https://docs.djangoproject.com/en/3.2/intro/tutorial05/#tests-make-your-code-more-attractive

Just a small suggestion from my side!

**Comment by seedlit** [comment]
Sure. I will add the tests and some checks as well to ensure the input DSM is in correct format.

**Comment by seedlit** [comment]
@R1j1t I have added the tests. Though, I also intend to create a makefile for automated testing, I will close this issue for now.
Thanks!
