### ISSUE TITLE
Issue on DSM to DTM Convertion for smoothness of cones

### ISSUE THREAD

**Issue by karthikgn** [seedlit/dsm2dtm#13]
Hai seedlit...!
I have issue on DSM to DTM convertion,I done by using the agisoft metashape  software but Cones is Created in buildings edges, i tried to smoothness of cones, By using your code DSM to DTM converted ,it came same as the agisoft ,i need  without cones (Please refer the image)
what are the parameters need to change in your code.
I attached the image also for reference..
I hope will get quick response.
Thank you... :) 
![1](https://github.com/seedlit/dsm2dtm/assets/28048671/32eb9340-e509-4346-989e-d36830a3f281)

**Comment by seedlit** [comment]
@karthikgn I would recommend to break your DSM into smaller sized DSMs. 
My recommendation would be to break this image into 4 different files and run dsm2dtm. 
Let me know if it worked.

Also, what are the dimensions of your input image (DSM)?

**Comment by karthikgn** [comment]
Thanks for Reply :)
yes,I did that one  but after some height it removes additional features i.e., additional terrain is getting removed please refer the image 1 and 2.

diemnsions
DSM
Length -1.145KM
Width  - 1.123KM
    or
Area   - 1.283 SQKM
1.
![Agisoft](https://github.com/seedlit/dsm2dtm/assets/28048671/2cd12978-2f6b-4ba7-a32b-9803acfaaaf4)

2.

![Python](https://github.com/seedlit/dsm2dtm/assets/28048671/87368487-4cd1-4a4c-bd0f-dfb1a4840c2a)

**Comment by seedlit** [comment]
Apologies for not being clear.
I meant dimensions in number of pixels :) 
And also what's the resolution of the image?
(since the params [calculation depend on the resolution of the image).](https://github.com/seedlit/dsm2dtm/blob/d82376217cc9badd2fb3b93800ffa067d71a02cc/dsm2dtm.py#L267)

**Comment by seedlit** [comment]
Additionally, I [started working on updating it sometime back](https://github.com/seedlit/dsm2dtm/blob/372028aa8dfdc49477c8c9ef63c7ea52e7a543cf/src/dsm2dtm.py#L282), but didn't manage to finish it yet.
Take a look if that helps as well.

**Comment by karthikgn** [comment]
Thanks ...!
Dimensions of the image
Length - 17175 pixel
Width  -  16845 pixel

Resolution of the image is 0.15 CM

**Comment by seedlit** [comment]
I would recommend to break it into smaller tiles of approx 3000*3000 pixels each.
Let me if that worked

**Comment by karthikgn** [comment]
Hai ...!
I Tried the Smaller Tiles like 3000*3000 Pixel Each.
Please refer the images as below
1.DSM
![DSM](https://github.com/seedlit/dsm2dtm/assets/28048671/e07651a8-b165-4620-a4be-7ba777fb8301)
2.DTM by using code
![DTM_Python](https://github.com/seedlit/dsm2dtm/assets/28048671/f1be61fb-6a31-4dd8-936d-8abe484b7b9a)

**Comment by seedlit** [comment]
still seem to be poor results.
Is it possible for you to share the DSM with me so I can try to play around a bit?

**Comment by karthikgn** [comment]
Share your email id so that i can share the data to you.

**Comment by seedlit** [comment]
`naman.jain@btech2015.iitgn.ac.in`

**Comment by seedlit** [comment]
@karthikgn I am closing the issue.
Please re-open if you need any help.
