### ISSUE TITLE
file missing issue?

### ISSUE THREAD

**Issue by Lee-inso** [seedlit/dsm2dtm#7]
ERROR 4: Attempt to create new tiff file `generated_dtm\temp_files\generated_dtm\temp_files\sample_dsm_ds_slp.tif' failed: No such file or directory
ERROR 1: Unable to create dataset generated_dtm\temp_files\generated_dtm\temp_files\sample_dsm_ds_slp.tif
ERROR 4: generated_dtm\temp_files\generated_dtm\temp_files\sample_dsm_ds_slp.tif: No such file or directory
Traceback (most recent call last):
  File "D:/PycharmProjects/pythonProject/dsm2dtm/dsm2dtm-main/dsm2dtm.py", line 359, in <module>
    dtm_path = main(dsm_path, out_dir)
  File "D:/PycharmProjects/pythonProject/dsm2dtm/dsm2dtm-main/dsm2dtm.py", line 304, in main
    avg_slp = int(get_mean(dsm_slp_path))
  File "D:/PycharmProjects/pythonProject/dsm2dtm/dsm2dtm-main/dsm2dtm.py", line 55, in get_mean
    np_raster = np.array(gdal.Open(raster_path).ReadAsArray())
AttributeError: 'NoneType' object has no attribute 'ReadAsArray'

**Comment by lee910213** [comment]
ground_dem_filtered_path = 'XXX\\dsm2dtm-main\\data\\sample_dsm_ds_ground_filtered.tif'
there is no such file

**Comment by lee910213** [comment]
def extract_dtm(dsm_path, ground_dem_path, non_ground_dem_path, radius, terrain_slope):
    """
    Generates a ground DEM and non-ground DEM raster from the input DSM raster.
    Input:
        dsm_path: {string} path to the DSM raster
        radius: {int} Search radius of kernel in cells.
        terrain_slope: {float} average slope of the input terrain
    Output:
        ground_dem_path: {string} path to the generated ground DEM raster
        non_ground_dem_path: {string} path to the generated non-ground DEM raster
    """
    cmd = "saga_cmd grid_filter 7 -INPUT {} -RADIUS {} -TERRAINSLOPE {} -GROUND {} -NONGROUND {}".format(
        dsm_path, radius, terrain_slope, ground_dem_path, non_ground_dem_path
    )
    os.system(cmd)

I try the tests.py
this function can not create the ground DEM raster & non-ground DEM raster files
I consider that I should deal with the saga_cmd on win platform

**Comment by lee910213** [comment]
saga_cmd issue had been solved, after add the saga_cmd.exe path.
Then, I try the tests.py. 

Traceback (most recent call last):
  File "D:/PycharmProjects/pythonProject/dsm2dtm/dsm2dtm-main/tests.py", line 43, in <module>
    assert os.path.isfile(diff_raster_path)
AssertionError

GDAL was installed by "conda install gdal==3.4.3"
Next, I need to check how gdal_calc.py work.

def subtract_rasters(rasterA_path, rasterB_path, out_path, no_data_value=-99999.0):
    cmd = 'gdal_calc.py -A {} -B {} --outfile {} --NoDataValue={} --calc="A-B"'.format(
        rasterA_path, rasterB_path, out_path, no_data_value
    )
    os.system(cmd)

**Comment by Lee-inso** [comment]
I verify the cmd str, add 'python' in thf front, and copy the gdal_calc.py to the local root.

def subtract_rasters(rasterA_path, rasterB_path, out_path, no_data_value=-99999.0):
    cmd = 'python gdal_calc.py -A {} -B {} --outfile {} --NoDataValue={} --calc="A-B"'.format(
        rasterA_path, rasterB_path, out_path, no_data_value
    )
    os.system(cmd)

Now the tests.py work
__________
total execution time: 0 milliseconds (less than 1 millisecond)

[Close Gaps] Execution succeeded (less than 1 millisecond)
Saving grid: test_results\temp_files\sample_dsm_dtm.sdat...

100%
okay
All tests passed!

But, when I run the dtm2dsm.py, there are double 'generated_dtm\\temp_files' in the raster_path str.
raster_path = 'generated_dtm\\temp_files\\generated_dtm\\temp_files\\sample_dsm_ds_slp.tif'

**Comment by Lee-inso** [comment]
I verify "/"to"\\", then the dsm2dtm.py work well
Thank you, nice repo!

 # Generate DTM
    # STEP 1: Generate slope raster from dsm to get average slope value
    dsm_name = dsm_path.split("\\")[-1].split(".")[0]
    dsm_slp_path = os.path.join(temp_dir, dsm_name + "_slp.tif")
    generate_slope_raster(dsm_path, dsm_slp_path)
    avg_slp = int(get_mean(dsm_slp_path))

total execution time: 0 milliseconds (less than 1 millisecond)

[Close Gaps] Execution succeeded (less than 1 millisecond)
Saving grid: generated_dtm\temp_files\sample_dsm_ds_dtm.sdat...

100%
okay
######### DTM generated at:  generated_dtm\sample_dsm_ds_dtm.tif
