### ISSUE TITLE
Use of your DSM to DTM code on GITHUB

### ISSUE THREAD

**Issue by NISHANTHMP** [seedlit/dsm2dtm#9]
I  have been able to run the code and it took my entire day to run, i have low number of processor.

Now I am facing the error which I have attached as an attachment. 

Please do respond to it and suggest me so method or modification that i need to do. This is my last resort, I need the DTM for flood modelling. Any insight will be helpful. 
![Screenshot (102)](https://user-images.githubusercontent.com/113767950/227724179-b7231c1b-fe23-427a-8e7d-e9c1a36b5e6f.png)

**Comment by seedlit** [comment]
@NISHANTHMP  sorry, a bit too late.
Are you still facing this issue?
